pipeline {
    agent {
        node {
            label 'docker-agent-node'
        }
    }

    environment {
        CI = 'true'
        REMOTE_USER = 'vriera-server'
        REMOTE_HOST = '186.139.150.69'
        REMOTE_PORT = '7022'
        REMOTE_DIRECTORY = '/home/vriera-server/redes/builds'
    }
    
    stages {
        stage('pull') {
            
            steps{ 
                checkout([$class: 'GitSCM', 
                                                branches: [[name: '*/main']],
                                                userRemoteConfigs: [[credentialsId:'ssh-key' , url: 'https://github.com/szavalia/todo-app']]])
                echo "${WORKSPACE}"
                 sh "ls -lat"
            } 
        }
        stage('Fetch') {
            steps{ 

                echo "Fetching 💡"
                sh '''
                  sh "ls -lat"
                  echo "$PWD"
                  ls
                  yarn install --silent --frozen-lockfile
                '''
            } 
        }
        stage('Test') {
            steps { 
                echo "Testing ️🥊"
                sh '''
                yarn test
                '''
            }
        }
        stage('Build') {
            
            steps {
                // You can add your build steps here
                echo "Building 🛠️"
                sh '''
                yarn build
                '''
            }
        }
        stage('Deploy') {
            steps {
                input(message: 'Deploy to production?', ok: 'Deploy', submitter: 'admin')
                
                echo "Deploying 🚀"

                // Copy the build to the remote server
                sshagent(credentials: ['ssh-key']) {
                    sh 'scp -P $REMOTE_PORT -o StrictHostKeyChecking=no -r build/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIRECTORY/$BUILD_ID'
                }

                // Deploy the build on the remote server
                sshagent(credentials: ['ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no -p 7022 vriera-server@186.139.150.69 ./redes/deploy.sh
                    '''
                }
            }
        }
    }

    post {
      failure {
        echo "Build failed 😞"
        emailext body: "Build failed 😞", subject: "Build failed 😞", to: 'val-riera@hotmail.com'
      }
      success { 
        echo "Build succeeded 😊"
        emailext body: "Build succeeded 😊", subject: "Build succeeded 😊", to: 'val-riera@hotmail.com'
      }
    }
}