pipeline {
    agent {
        node {
            label 'docker-agent-node'
        }
    }

    environment {
        CI = 'true'
        

    }
    
    stages {
        stage('Fetch') {
            steps{ 
                echo "Fetching 💡"
                // sh '''
                //   yarn install --silent --frozen-lockfile
                // '''
            } 
        }
        stage('Test') {
            steps { 
                echo "Testing ️🥊"
                // sh '''
                // yarn test
                // '''
            }
        }
        stage('Build') {
            environment {
                SSH_KEY = credentials('SSH_KEY') 
                REMOTE_USER = 'vriera-server'
                REMOTE_HOST = '186.139.150.69'
                REMOTE_PORT = '7022'
                REMOTE_DIRECTORY = '/redes/builds'
            }
            steps {
                // You can add your build steps here
                echo "Building 🛠️"
                // sh '''
                // yarn build
                // '''
                mkdir build
                touch build/test.txt

                // echo 'scp -P ${env.REMOTE_PORT} -r build/ ${env.REMOTE_USER}@${env.REMOTE_HOST}:${env.REMOTE_DIRECTORY}'
                
                // Copy the build to the remote server
                sshagent(['SSH_KEY']) {
                sh 'scp -P ${env.REMOTE_PORT} -r build/ ${env.REMOTE_USER}@${env.REMOTE_HOST}:${env.REMOTE_DIRECTORY}'
                }
            }
        }
        // stage('Deploy') {
        //     steps {
        //         input(message: 'Deploy to production?', ok: 'Deploy', submitter: 'admin')

        //         echo "Deploying 🚀"
        //         // Deploy the build on the remote server
        //         sshagent(['SSH_KEY']) {
        //             sshCommand remote: "${env.REMOTE_USER}@${env.REMOTE_HOST}", port: env.REMOTE_PORT, 
        //             command: "cd ${env.REMOTE_DIRECTORY} && ls "
        //         }
        //     }
        // }
    }

    // post {
    //   failure {
    //     echo "Build failed 😞"
    //     emailext body: "Build failed 😞", subject: "Build failed 😞", to: 'szavalia@itba.edu.ar'
    //   }
    //   success { 
    //     echo "Build succeeded 😊"
    //     emailext body: "Build succeeded 😊", subject: "Build succeeded 😊", to: 'szavalia@itba.edu.ar'
    //   }
    // }
}